# -*- coding: utf-8 -*-
"""Test1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QQXEFNw56Wxw2c2MiBG8Sqk2taQMfZN
"""

# # Install DeepFace and other dependencies
# !pip install deepface opencv-python-headless scikit-learn

"""# Face Enrollment & Recognition — Test 1
**Project:** Capstone — Student Face Enrollment & Recognition (Video-based collection)  
**Version:** Test 1

**Overview:**  
This notebook provides an end-to-end pipeline to:
1. Accept one pre-recorded `.mp4` video per student (covering front, left, right views).  
2. Extract frames and detect faces using `deepface`.  
3. Compute face embeddings (128-dimensional).  
4. Save embeddings to disk per student as `<ROLL>.npy`.  
5. Build a dataset from saved enrollment files, train an SVM classifier, and evaluate performance.  
6. Recognize a student from a provided front-facing image and report confidence.

**Technology Used:**
- Python 3 (Colab default)
- OpenCV for video processing
- DeepFace for face detection and recognition
- NumPy for storing embeddings
- scikit-learn for optional classifier training



"""

import cv2
import numpy as np
from deepface import DeepFace
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib
import json
from scipy.spatial.distance import cosine
from google.colab import files
from PIL import Image
from typing import List, Tuple, Dict
from pathlib import Path

"""# Initialization and configuration
Set up basic configuration variables and a working directory for enrollment files. Files are saved to Google Drive. For Test 1 we will save per-student embeddings in `enrollments/` as `<ROLL>.npy`.

"""

# Define local directories for enrollment and models
BASE_DIR = Path("./capstone_data")
BASE_DIR.mkdir(parents=True, exist_ok=True)

WORKDIR = BASE_DIR / "enrollments"
MODEL_DIR = BASE_DIR / "models"
WORKDIR.mkdir(exist_ok=True)
MODEL_DIR.mkdir(exist_ok=True)

print("Local storage initialized.")
print("Enrollment directory:", WORKDIR)
print("Model directory:", MODEL_DIR)

"""# Extract frames from a video and compute embeddings using DeepFace
- Frames are extracted every N frames to reduce redundancy.
- Each frame is passed through DeepFace (Facenet) to compute 128-d embeddings.
- Aggregated embeddings are averaged per student enrollment.

"""

def extract_frames_from_video(video_path: str, frame_interval: int = 5) -> List[np.ndarray]:
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise IOError(f"Cannot open video file {video_path}")
    frames = []
    idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if idx % frame_interval == 0:
            frames.append(frame.copy())
        idx += 1
    cap.release()
    return frames

def frames_to_embeddings(frames: List[np.ndarray]) -> np.ndarray:
    embeddings = []
    for frame in frames:
        try:
            emb = DeepFace.represent(frame,model_name="Facenet", detector_backend="mtcnn", enforce_detection=True)
            embeddings.append(np.array(emb[0]["embedding"]))
        except:
            pass
    if not embeddings:
        return np.empty((0,128))
    return np.vstack(embeddings)

"""# Enrollment Process
- Upload a student video (`.mp4`).
- Prompt for roll number.
- Extract frames, compute embeddings, and save averaged embedding as `<ROLL>.npy`.
- Metadata (roll, name, source file) saved as JSON.

"""

def enroll_from_uploaded_video(frame_interval: int = 5):
    print("Upload the student's .mp4 video file.")
    uploaded = files.upload()
    if not uploaded:
        print("No file uploaded.")
        return

    fname = next(iter(uploaded))
    with open(fname, "wb") as f:
        f.write(uploaded[fname])
    print(f"Saved uploaded file to {fname}.")

    roll = input("Enter student roll number (used as filename): ").strip()
    student_name = input("Enter student name (optional): ").strip()

    frames = extract_frames_from_video(fname, frame_interval)
    print(f"Extracted {len(frames)} frames. Computing embeddings...")
    encs = frames_to_embeddings(frames)
    print(f"Computed embeddings for {encs.shape[0]} frames.")

    if encs.shape[0] == 0:
        print("No embeddings computed. Enrollment failed.")
        return

    # Compute mean embedding for the student
    mean_embedding = np.mean(encs, axis=0)

    out_path = WORKDIR / f"{roll}.npy"
    np.save(out_path, mean_embedding)

    meta = {"roll": roll, "name": student_name, "source_file": fname}
    with open(WORKDIR / f"{roll}.json", "w") as jf:
        json.dump(meta, jf)

    print(f"Enrollment saved: {out_path}")
    return out_path

"""## Run the cell below to upload video."""

# Interactive enrollment — triggers video upload prompt
enroll_from_uploaded_video()

"""# For Batch Enrollement"""

# Batch Enrollment — Upload multiple videos at once
from google.colab import files

def batch_enroll_videos(frame_interval: int = 5, model: str = "Facenet"):
    """
    Upload multiple .mp4 videos for enrollment.
    Each video will prompt for the corresponding roll number.
    Embeddings are saved to WORKDIR as <ROLL>.npy.
    """
    print("Upload multiple .mp4 videos for enrollment (hold Ctrl to select multiple).")
    uploaded = files.upload()
    if not uploaded:
        print("No files uploaded. Aborting batch enrollment.")
        return

    for fname in uploaded.keys():
        print(f"\nProcessing file: {fname}")
        # Save uploaded file to disk
        with open(fname, "wb") as f:
            f.write(uploaded[fname])

        # Prompt for roll number
        roll = input(f"Enter roll number for {fname}: ").strip()
        student_name = input(f"Enter student name for {fname} (optional): ").strip()

        # Extract frames
        try:
            frames = extract_frames_from_video(fname, frame_interval=frame_interval)
        except Exception as e:
            print("Error reading video:", e)
            continue

        print(f"Extracted {len(frames)} frames. Running face detection...")

        # Compute embeddings using DeepFace
        encs = []
        for frame in frames:
            try:
                emb = DeepFace.represent(frame, model_name="Facenet", enforce_detection=True)
                encs.append(np.array(emb[0]["embedding"]))
            except:
                continue

        if len(encs) == 0:
            print(f"No faces detected in {fname}. Skipping...")
            continue

        encs_array = np.vstack(encs)
        out_path = WORKDIR / f"{roll}.npy"
        np.save(out_path, encs_array)

        # Save metadata
        meta = {"roll": roll, "name": student_name, "source_file": fname}
        with open(WORKDIR / f"{roll}.json", "w") as jf:
            import json
            json.dump(meta, jf)

        print(f"Saved enrollment for {roll} with {encs_array.shape[0]} embeddings.")

    print("\nBatch enrollment complete!")

batch_enroll_videos()

"""# Build dataset for training
- Load all saved `.npy` files from `enrollments/`.
- Each student's embeddings are labeled with their roll number.
- Output: X (N×128 embeddings), y (labels), label_map (int->roll mapping)


"""

def find_enrollment_files(enroll_dir: Path = WORKDIR) -> List[Path]:
    return sorted(list(enroll_dir.glob("*.npy")))

def build_dataset_from_npy_files(enroll_files: List[Path]) -> Tuple[np.ndarray, np.ndarray, Dict[int,str]]:
    X_parts, y_parts = [], []
    label_map = {}
    current_label = 0
    for f in enroll_files:
        roll = f.stem
        encs = np.load(f)
        if encs.size == 0:
            continue
        label_map[current_label] = roll
        X_parts.append(encs)
        y_parts.append(np.full((encs.shape[0],), current_label, dtype=int))
        current_label += 1
    if not X_parts:
        return np.empty((0,128)), np.array([], dtype=int), label_map
    X = np.vstack(X_parts)
    y = np.concatenate(y_parts)
    return X, y, label_map

# Build dataset
enroll_files = find_enrollment_files()
print("Enrollment files:", enroll_files)
X, y, label_map = build_dataset_from_npy_files(enroll_files)
print("Dataset shapes -> X:", X.shape, "y:", y.shape)

"""# Train SVM classifier
- Split dataset into train/test.
- Train a linear SVM on embeddings.
- Evaluate test accuracy, classification report, and confusion matrix.
- Save model and label_map for future inference.
  
"""

def train_svm_and_evaluate(X, y, label_map, test_size=0.2, random_state=42):
    if X.shape[0] == 0:
        print("No data available for training.")
        return None, {}
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y)

    clf = SVC(kernel='linear', probability=True)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    cm = confusion_matrix(y_test, y_pred)

    print(f"Training complete. Test accuracy: {acc:.4f}")
    return clf, {"accuracy": acc, "report": report, "confusion_matrix": cm, "label_map": label_map}

if X.shape[0] > 0:
    clf, results = train_svm_and_evaluate(X, y, label_map)
    joblib.dump(clf, MODEL_DIR / "svm_face_recognition.joblib")
    with open(MODEL_DIR / "label_map.json", "w") as f:
        json.dump(label_map, f)
    print("Saved model and label map.")
else:
    print("No enrollment data. Enroll students first.")

# Print accuracy and detailed classification report
if 'results' in globals() and results:
    print(f"Test Accuracy: {results['accuracy']:.4f}")
    from pprint import pprint
    pprint(results['report'])
    print("Confusion Matrix:\n", results['confusion_matrix'])
else:
    print("No training results available. Make sure you trained the model with enrollments first.")

"""# Recognize student from uploaded image
- Upload a front-facing image.
- Detect face, compute embedding, predict roll number using trained SVM.

"""

def recognize_from_uploaded_image(model_path: str = str(MODEL_DIR / "svm_face_recognition.joblib"),
                                  label_map_path: str = str(MODEL_DIR / "label_map.json")):
    if not Path(model_path).exists() or not Path(label_map_path).exists():
        print("Model or label_map not found. Train the model first.")
        return None
    clf = joblib.load(model_path)
    with open(label_map_path, "r") as f:
        label_map = json.load(f)
    inv_map = {int(k): v for k, v in label_map.items()}

    print("Upload front-facing image (jpg/png).")
    uploaded = files.upload()
    if not uploaded:
        print("No file uploaded.")
        return None
    fname = next(iter(uploaded))
    with open(fname, "wb") as f:
        f.write(uploaded[fname])

    pil = Image.open(fname).convert("RGB")
    display(pil.resize((320,320)))

    frame = np.array(pil)
    try:
        emb = DeepFace.represent(frame, model_name="Facenet",detector_backend="mtcnn", enforce_detection=True)
        emb_array = np.array(emb[0]["embedding"]).reshape(1,-1)
    except:
        print("No face detected.")
        return None

    pred = clf.predict(emb_array)[0]
    try:
        conf = float(np.max(clf.predict_proba(emb_array)))
    except:
        conf = None
    roll_pred = inv_map.get(int(pred), "Unknown")
    print(f"Predicted roll: {roll_pred} (label {pred}) Confidence: {conf}")
    return roll_pred, conf

"""## Run cell below to verify face"""

# Interactive recognition — triggers image upload prompt
recognize_from_uploaded_image()

"""##**Approach 2**
## Cosine Matching: Recognition Using Mean Embeddings


- Instead of training an SVM, we compute a mean embedding per student from all their frames in the enrollment video.

- To recognize a new image: compute its embedding and compare it with all mean embeddings using cosine distance.

- **Threshold**: Determines how similar the embeddings need to be to consider a match. A lower threshold = stricter match (less false positives), a higher threshold = looser match (may accept similar but different faces).

This method works well for small datasets and can scale to thousands of students later, as we only compare vectors, no classifier training required.
"""

enroll_files = sorted(list(WORKDIR.glob("*.npy")))
X_mean_list, y_mean_list = [], []
label_map_mean = {}
for idx, f in enumerate(enroll_files):
    arr = np.load(f)  # shape (N, D) or maybe (D,) if saved differently
    if arr.ndim == 1:
        # if someone saved a single mean already
        emb = arr
    else:
        emb = arr.mean(axis=0)
    X_mean_list.append(emb)
    y_mean_list.append(idx)
    label_map_mean[idx] = f.stem

if X_mean_list:
    X_mean = np.vstack(X_mean_list)
    y_mean = np.array(y_mean_list)
    print("X_mean shape:", X_mean.shape, "y_mean shape:", y_mean.shape)
    print("label_map_mean:", label_map_mean)
else:
    print("No enrollment embeddings found for mean aggregation.")


from scipy.spatial.distance import cosine
def recognize_with_means(image_path, threshold=0.6):
    img = cv2.imread(image_path)
    try:
        emb_array = frames_to_embeddings([img])
        if emb_array.shape[0] == 0:
            print("No face detected in the image.")
            return
    except Exception as e:
        print(f"Error processing image: {e}")
        return

    enroll_files = sorted(list(WORKDIR.glob("*.npy")))
    X_mean_list, y_mean_list = [], []
    label_map_mean = {}
    for idx, f in enumerate(enroll_files):
        mean_emb = np.load(f)
        X_mean_list.append(mean_emb)
        y_mean_list.append(idx)
        label_map_mean[idx] = f.stem

    X_mean = np.vstack(X_mean_list)
    scores = [cosine(emb_array[0], mean) for mean in X_mean]
    best_idx = np.argmin(scores)
    best_score = scores[best_idx]

    if best_score > threshold:
        print("No match found. Closest score exceeds threshold.")
        return

    roll_pred = label_map_mean[best_idx]
    print(f"Predicted roll: {roll_pred} (cosine distance: {best_score:.4f})")
    return roll_pred


# print(recognize_with_means('false.jpg', threshold=0.6))

from google.colab import files
from PIL import Image
from IPython.display import display

def recognize_with_means_upload(threshold=0.6):
    """
    Opens Colab upload dialog, then calls the existing recognize_with_means(image_path, threshold).
    Keeps your original logic unchanged.
    """
    print("Upload a front-facing image (jpg/png) for recognition.")
    uploaded = files.upload()
    if not uploaded:
        print("No file uploaded.")
        return None, None

    fname = next(iter(uploaded))
    # save uploaded file to current working directory (so your original function can read it)
    with open(fname, "wb") as f:
        f.write(uploaded[fname])

    # show uploaded image for confirmation
    try:
        pil = Image.open(fname).convert("RGB")
        display(pil.resize((320,320)))
    except:
        pass

    # call your existing function (no modifications needed)
    return recognize_with_means(fname, threshold=threshold)

recognize_with_means_upload(threshold=0.6)